services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./env/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./env/certs:/etc/nginx/certs
      - ./pub:/app/pub
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./src:/app/src
      - ./pub:/app/pub
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: {}
